"""add access point table

Revision ID: 3fdf2e94303a
Revises: 64ae574e8dc2
Create Date: 2023-12-11 17:37:58.994223

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "3fdf2e94303a"
down_revision = "64ae574e8dc2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "access_point",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("rental_unit_id", sa.String(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column(
            "permission",
            postgresql.ENUM(
                "CAN_SEE_GATEWAYS",
                "IS_ADMIN",
                "IS_MANAGER",
                "IS_GUEST",
                "IS_HOST",
                "IS_SUPPORT",
                "IS_REPORTING",
                "IS_OPERATIONS",
                "IS_SUPERUSER",
                name="permissionenum",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["rental_unit_id", "organization_id"],
            ["rental_unit.id", "rental_unit.organization_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("access_point")
    # ### end Alembic commands ###
