"""add tenant

Revision ID: 64ae574e8dc2
Revises: 2f786c659c81
Create Date: 2023-12-13 19:26:50.612628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "64ae574e8dc2"
down_revision = "2f786c659c81"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenants",
        sa.Column("id", sa.String(length=63), nullable=False),
        sa.Column("external_id", sa.String(), nullable=True),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("email_address", sa.String(), nullable=True),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.CheckConstraint(
            "id ~* '^[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?$'",
            name="id_format_check",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id", "organization_id"),
        sa.UniqueConstraint("email_address", "organization_id"),
        sa.UniqueConstraint("external_id", "organization_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tenants")
    # ### end Alembic commands ###
